### ISSUE TITLE
Manual inline

### ISSUE THREAD

**Issue by ai** [borodean/postcss-assets#1]
Automatic inline by file size is a bad way (it is come from early Grunt tools). For example, I connect font files and I know, that italic bold version is used very rare. So I should have some `inline()` function:

``` css
@font-face {
  font-family: "Franklin Gothic";
  font-weight: normal;
  font-style: normal;
  src: inline("franklin-gothic/regular.woff") format("woff");
}

@font-face {
  font-family: "Franklin Gothic";
  font-weight: bold;
  font-style: normal;
  src: inline("franklin-gothic/demi.woff") format("woff");
}

@font-face {
  font-family: "Franklin Gothic";
  font-weight: bold;
  font-style: italic;
  src: font-url("franklin-gothic/demi-italic.woff") format("woff");
}
```

In Rails Assets we no use [Rails Sass Images](https://github.com/ai/rails-sass-images) for this tasks with `inline` function.

/cc @borodean
