### ISSUE TITLE
Windows problem: backslashes returned for css output

### ISSUE THREAD

**Issue by aproc** [borodean/postcss-assets#19]
I'm on a Windows machine and using postcss-assets. When I use resolve() in combination with the 'relativeTo' option, I receive double backslashes as css output instead of a simple /

```scss
/* source input: */
.selector { background-image: resolve('filename.png'); }
```

```css
/* generated output: */
.selector { background-image: url('..\\images\\filename.png'); }
```

```css
/* expected output: */
.selector { background-image: url('../images/filename.png'); }
```
