### ISSUE TITLE
Are you able to glob loadPaths?

### ISSUE THREAD

**Issue by DanGamble89** [borodean/postcss-assets#31]
Sometimes we have multiple folders inside the `img` folder but they are different per project so i wouldn't be able to add them all the the loadPaths. If this is available or was added how does it deal with name conflicts?

**Comment by DanGamble89** [comment]
I have just realised i could theoretically just include the base file then use a path before the filename. Would still be interested about globbing :)

**Comment by borodean** [comment]
@DanGamble89 well, what I do in such cases is specify image path in a more explicit fashion indeed. For instance, if I have `images` directory containing `backgrounds` and `icons`, I set `images` as `basePath` and resolve image paths like this:

```css
body {
  background: resolve('backgrounds/clouds.jpg');
}

.search {
  background: resolve('icons/search.svg') no-repeat center center;
}
```

As a frontend developer I see no need for globbing here.
