### ISSUE TITLE
Relative path from current CSS file

### ISSUE THREAD

**Issue by ai** [borodean/postcss-assets#7]
When I write

```css
@font-face {
    src: inline("./demi.woff")
}
```

I expect that it takes file from same dir as CSS files.

You can take CSS file path from `decl.source.input.file`.
